site_name: Journey through self-hosting
site_description: A beginner-friendly learning journal about self-hosting and homelabbing.
site_url: https://juscghwe.github.io/Journey-through-self-hosting/
site_author: juscghwe
copyright: Copyright (c)2025 juscghwe

repo_name: juscghwe/Journey-through-self-hosting
repo_url: https://github.com/juscghwe/Journey-through-self-hosting

theme:
  name: 'material'
  custom_dir: 'overrides/'
  features:
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - content.action.edit

nav:
  - Home: index.md
  - Personal background: 00-personal-background.md
  - What's homelabbing: 01-introduction-homelabbing.md

edit_uri: edit/main/docs/

plugins:
  - search
#  - awesome-pages

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg